### ISSUE TITLE
Prop `width` on documentation has no implementation

### ISSUE THREAD

**Issue by lucis** [vtex-apps/flex-layout#33]
Docs for **flex.layout-col**:
![image](https://user-images.githubusercontent.com/18706156/82596648-075de500-9b7e-11ea-96b7-6086bb3ff5b5.png)

But it's a prop that has no effect and has no implementation on source code.

**Comment by rafael-marques** [comment]
Hi @lucis 

I got the same problem. Did you find a way to set the column width?
